web/adminLandingPage.jsp

voter landing,lading2 -nitish

---

web/menu.jsp

Final menu shirshak do changes please

Final menu shirshak do changes

---

web/adminLandingPage.jsp
web/assets/css/style.css
web/assets/css/voterLanding.css
web/landingPage.jsp
web/login.jsp
web/menu.jsp
web/signup.jsp

menu edit-Shirshak

---

src/java/com/exavalu/models/Candidate.java
src/java/com/exavalu/models/User.java
src/java/com/exavalu/models/Voter.java
src/java/com/exavalu/services/CandidateService.java
src/java/com/exavalu/services/VoterService.java

Shouvik Final candidate services

---

src/java/com/exavalu/models/Admin.java
src/java/com/exavalu/services/AdminService.java
web/voterLandingPage.jsp

Admin approve voter-Shirshak

---

src/java/com/exavalu/models/Voter.java
src/java/com/exavalu/services/VoterService.java

voting services

---

src/java/com/exavalu/models/Voter.java
src/java/com/exavalu/services/VoterService.java
src/java/struts.xml
web/assets/css/voterLanding.css
web/login.jsp
web/menu.jsp
web/voterLandingPage.jsp

voting services2

---

src/java/com/exavalu/models/Voter.java
src/java/com/exavalu/services/VoterService.java
src/java/struts.xml
web/candidateDetails.jsp
web/candidateInput.jsp
web/detailsOfVoter.jsp

ankit(reject voter)

---

src/java/com/exavalu/models/User.java
src/java/com/exavalu/models/Voter.java
web/detailsOfVoter.jsp
web/menu.jsp
web/voterLandingPage.jsp
web/voterList.jsp

voter work 27/2/23

---

src/java/com/exavalu/models/Voter.java
web/voterLandingPage.jsp

voter work 27/2/23 P3

---

src/java/com/exavalu/models/Result.java
src/java/com/exavalu/services/ResultService.java
src/java/struts.xml
web/adminResult.jsp
web/candidateResult.jsp

login correction Shouvik

---

src/java/com/exavalu/models/CandidateAPI.java
web/candidateIdentityDetails.jsp

candidateAPI

---

src/java/com/exavalu/models/Candidate.java
src/java/com/exavalu/services/CandidateService.java
src/java/struts.xml
web/candidateDetails.jsp
web/candidateEdit.jsp

Edit Candidate Final- Shirshak

---

web/detailsOfVoter.jsp
web/voterIdentityDetails.jsp
web/voterList.jsp

FixedVoterList-Anjali

---

src/java/com/exavalu/models/Result.java
src/java/com/exavalu/services/ResultService.java
src/java/struts.xml
web/adminResult.jsp

vote begin end Shouvik

---

src/java/com/exavalu/models/Result.java
src/java/struts.xml
web/menu.jsp

Reverts shirshakbanerjee/OnlineVotingsystem#40

Revert "Start End Feature Shouvik"

---

src/java/com/exavalu/models/Email.java
src/java/com/exavalu/models/Result.java
web/menu.jsp
web/signup.jsp

email to candidate result

---

src/java/com/exavalu/models/Email.java

candidate edit email- Shirshak

---

src/java/com/exavalu/models/Result.java
src/java/com/exavalu/models/Voter.java
src/java/com/exavalu/services/ResultService.java
src/java/com/exavalu/services/VoterService.java
web/adminResult.jsp

Bah Wah WAh Badhiya Come back after 2pm

Kitna sikhoge aur

---

src/java/com/exavalu/models/User.java
src/java/com/exavalu/services/UserService.java
web/login.jsp

otp fix- Shirshak

---

src/java/com/exavalu/models/Email.java
src/java/com/exavalu/models/Result.java
src/java/com/exavalu/models/Voter.java
web/adminResult.jsp
web/resultNotDeclared.jsp

email fixed ,resultNotDeclared Jsp has some spelling mistake ,,don't include that

candidate and voter mail fixed

---

web/adminResult.jsp

adminResult fixed

---

web/resultNotDeclared.jsp

result time

---

src/java/com/exavalu/models/User.java
src/java/com/exavalu/services/UserService.java
src/java/struts.xml
web/VoterFeedback.jsp
web/candidateInput.jsp
web/login.jsp
web/menu.jsp

fixed Login

---

src/java/com/exavalu/models/CandidateAPI.java
web/candidateEdit.jsp
web/signup.jsp

CandidateAPIsignup(ankit)

---

src/java/com/exavalu/models/Result.java
src/java/com/exavalu/services/AdminService.java
src/java/com/exavalu/services/CandidateService.java
src/java/com/exavalu/services/PartyService.java
src/java/com/exavalu/services/ResultService.java
src/java/com/exavalu/services/UserService.java
src/java/com/exavalu/services/VoterService.java
src/java/com/exavalu/utils/JDBCConnectionManager.java
src/java/com/exavalu/utils/JDBCUtility.java
src/java/com/exavalu/utils/Log4jDemo.java
src/java/log4j.properties
web/adminResult.jsp
web/voterList.jsp

LOG4 fixed

---

web/detailsOfVoter.jsp
web/voterList.jsp

voter reject work

---

web/signup.jsp

signupValidation1(ankit)

---

web/candidateIdentityDetails.jsp

Verified Add candidate

---

src/java/com/exavalu/models/VoterAPI.java

voterApi(Ankit)

---

src/java/com/exavalu/services/UserService.java
src/java/com/exavalu/services/VoterService.java

password md5

---

pmd-report.html
src/java/com/exavalu/models/Admin.java
src/java/com/exavalu/models/Candidate.java
src/java/com/exavalu/models/User.java
src/java/com/exavalu/models/Voter.java
src/java/com/exavalu/services/PartyService.java
src/java/com/exavalu/services/VoterService.java

PMDpriyanka

---

pmd-report.html
src/java/com/exavalu/models/Candidate.java
src/java/com/exavalu/models/Result.java
src/java/com/exavalu/models/User.java
src/java/com/exavalu/services/CandidateService.java

feature-PMDchange2

---

src/java/com/exavalu/models/Result.java
src/java/com/exavalu/services/ResultService.java

removed comments and deleted unused jsp

---

web/login.jsp
web/signup.jsp

signup-page-change
